name: "Client Setup"
description: "FEのCIの各Jobに必要なセットアップ処理をまとめたAction"

runs:
  using: "composite"
  steps:
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: "pnpm"
        cache-dependency-path: pnpm-lock.yaml

    # Enable pnpm using corepack
    - name: Enable pnpm with corepack
      run: corepack enable pnpm
      shell: bash

    # キャッシュされたnode_modulesを取得する
    - name: Restore node_modules Cache
      id: node_modules_cache
      uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('pnpm-lock.yaml') }}

    # キャッシュが存在しなかったら、pnpm installする
    - name: Install Dependencies
      if: ${{ steps.node_modules_cache.outputs.cache-hit != 'true' }}
      run: pnpm install
      shell: bash
