name: "Restore or Build Storybook"
description: "キャッシュに保存されているStorybookのビルド成果物を再利用する。(保存されていなかった場合はビルドする)"

runs:
  using: "composite"
  steps:
    - name: Get commit hash of current branch
      id: get_hash
      run: echo "hash=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
      shell: bash
    # キャッシュされたStorybookのビルド成果物を取得する
    - name: Restore cached storybook build result
      id: storybook_cache
      uses: actions/cache@v4
      with:
        path: storybook-static
        key: ${{ runner.os }}-storybook-static-${{ steps.get_hash.outputs.hash }}
    # キャッシュが存在しなかったら、Storybookをビルドする(Job終了時にビルド成果物はキャッシュされます)
    - name: Build Storybook
      if: ${{ steps.storybook_cache.outputs.cache-hit != 'true' }}
      run: pnpm storybook:build
      working-directory: client
      shell: bash